config/routes.rb
Teamsubs::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  devise_for :users
  match '/auth/facebook/' => 'authentications#facebook', :as => 'facebook_connect', via: [:get, :post]

  resources :users, only: [:show, :index]

  resources :events do
    member do
      get :duplicate_for_next_week
      get :resend_invitations
      get :new_email
      put :deliver_email
      get :show_subs
      get :show_same_day_subs
    end
    collection do
      get :deliver_thank_yous
    end
    resources :invitations, only: [:create]
  end

  resources :sports, only: [] do
    member do
      get :locations
    end
  end

  resources :locations, only: [:new, :create, :show]
  resources :invitations, only: [:show, :edit, :update] do
    member do
      get :open_tracker
    end
  end

  match 'invite/:id/:token(/:response)' => 'invitations#respond_from_email', :as => 'invite_with_token', via: [:get, :post]
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]
  post 'sendgrid/events_callback' => 'sendgrid#events_callback'

  # LEGACY STUFF
  match 'invitation/:invite_hash' => 'invitations#legacy_respond_from_email', via: [:get, :post]
  match 'respondfromemail/:invite_hash' => 'invitations#legacy_respond_from_email', via: [:get, :post]
  match 'copy/:invite_hash' => 'events#legacy_duplicate', via: [:get, :post]

  # render nothing routes for devices that just won't quit requesting garbage routes
  [ 'wp-trackback.php',
    'apple-touch-icon-precomposed.png',
    'customer/account/forgotpassword',
    'forum'
  ].each do |garbage_path|
    match garbage_path => 'home#not_found', via: [:post, :get]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  # event times are all in "local to user time zone".  Stored as UTC in the db.  Display the times as they are stored,
  # there is no need to calculate time zone.
  acts_as_cached(version: 1, expires_in: 10.days)

  has_many :rosters
  has_many :invitations
  has_many :users, through: :invitations
  belongs_to :location
  has_one :sport, through: :location
  belongs_to :planner_user, class_name: 'User'

  # make the code more readable
  attr_accessor :no_invitations, :yes_invitations, :maybe_invitations, :not_yet_replied_invitations, :email_body

  validates_presence_of :start_time, :title, :description, :location

  delegate :sport, to: :location

  accepts_nested_attributes_for :rosters

  after_save :invite_players

  scope :upcoming, -> { where('`start_time` >= ?', Time.now) }
  scope :previous, -> { where('`start_time` < ?', Time.now) }

  def invite_players
    rosters.where(primary: true).each do |roster|
      roster.invite_all
    end
  end

  def invite_next(roster)
    roster.invite_one unless roster.all_invited?
  end

  def build_duplicate
    new_event = dup
    rosters.each do |roster|
      new_roster = roster.dup
      new_roster.users << roster.users
      new_event.rosters <<  new_roster
    end
    new_event
  end

  def deliver_thank_you
    return if thank_you_sent?
    InviteMailer.delay.thank_you(self)
    update_attributes(thank_you_sent: true)
  end

  def weather
    return nil unless location.has_latlon?
    cache_key = "event_#{id}_weather"
    Rails.cache.fetch(cache_key, expires_in: 1.day) do
      ForecastIO.forecast(location.latitude, location.longitude, time: zoneless_formatted_start_time)
    end
  end

  def possible_subs
    # used for finding other games to get subs from.
    # Get users who will be playing the same sport at the same place, at a similar time
    other_events = Event.where(location_id: location.id)
      .where('`start_time` > ?', start_time - 4.hours)
      .where('`start_time` < ?', start_time + 4.hours)
      .where('`start_time` <> ?', start_time)
      .where('`events`.`id` <> ?', id)

    invitations = other_events.map { |e| e.invitations.where(response: Invitation.yes) }
    # remove currently invited people to this event and those who don't want sub requests
    users = invitations.flatten.map { |i| i.user if i.user.allow_sub_requests? && !(self.users.include?(i.user)) }
    users = users.reject { |u| u.nil? }
  end

  def zoneless_formatted_start_time
    start_time.strftime '%Y-%m-%dT%H:%M:%S'
  end

  def sport_id
    sport ? sport.id : nil
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
  load_and_authorize_resource
  before_filter :authenticate_user!, except: [:deliver_thank_yous]

  def new
    # include the nested resources
    @event = Event.new
    new_roster = @event.rosters.build(primary: true)
    new_roster.users << current_user
    new!
  end

  def create
    @event = Event.new(permitted_params[:event].merge(
       planner_user_id: current_user.id
    ).permit!)
    create!
  end

  def index
    @events = current_user.events.includes(:location).order('`id` DESC').page(params[:page])
    index!
  end

  def edit
    # assure that there is at least one roster
    @event = Event.find(params[:id])
    @event.rosters.build(primary: true) if @event.rosters.empty?
    edit!
  end

  def show
    @event = Event.find(params[:id])
    load_responses
    @current_user_invitation = @all_invitations.select { |i| i.user == current_user }.first
    @current_user_invitation.mark_read if @current_user_invitation
    show!
  end

  def duplicate_for_next_week
    # make another event with the same everything a week after this
    # send to the edit view for confirmation
    new_event = @event.build_duplicate
    new_event.start_time = @event.start_time + 1.week
    @event = new_event
    render :edit
  end

  def resend_invitations
    @event.invitations.find_each do |invite|
      invite.deliver
    end
    redirect_to @event
  end

  # send an email to users -- show user picker
  def new_email
    @users = @event.users
  end

  # send an email to users -- send the email
  def deliver_email
    users = []
    params[:event][:user_ids].each do |user_id|
      users << User.find_by_id(user_id) if user_id.present?
    end
    users.each do |user|
      InviteMailer.delay.user_message(user, current_user, @event, params[:event][:email_body])
    end
    redirect_to @event
  end

  # show this event's sub list
  def show_subs
    all_possible_users = []
    @event.rosters.each do |roster|
      all_possible_users = all_possible_users + roster.users
    end
    # create a dummy invitation to allow simpleform to make compact code
    @invitation = Invitation.new
    @users = all_possible_users - @event.users
  end

  # show possible subs from other 'nearby' games
  def show_same_day_subs
    @users = @event.possible_subs
  end

  # legacy duplicate
  def legacy_duplicate
    invitation = Invitation.find_by_responsehash(params[:invite_hash])
    event = invitation.event
    redirect_to duplicate_for_next_week_event_path(event)
  end

  ## Collection actions ########################

  def deliver_thank_yous
    # send a note for all events that ended a day ago to the planner -- use the 5 hours offset because the server is UTC
    @events = Event.where('`start_time` > ?', 2.days.ago).where('`start_time` < ?', 5.hours.ago)
    @events.each do |event|
      event.deliver_thank_you
    end
    # display a page with the events in text suitable for emailing
    render layout: false
  end

  def permitted_params
    params.permit(event: [
      :title, :start_time, :planner_user_id, :userlist, :created_at,
      :updated_at, :responsevalue, :repsonsetext, :description, :location_id,
      :image, :reminder_sent, :thank_you_sent, :team_id, :league_id,
      :schedule_link, rosters_attributes: [:id, :comma_separated_emails, :primary]
    ])
  end

  private

  def load_responses
    # minimize db calls, do logic in ruby for faster processing
    @all_invitations = @event.invitations.includes(user: :facebook_authentications)
    @event.yes_invitations = @all_invitations.select { |i| i.response == Invitation.yes }
    @event.no_invitations = @all_invitations.select { |i| i.response == Invitation.no }
    @event.maybe_invitations = @all_invitations.select { |i| i.response == Invitation.maybe }
    @event.not_yet_replied_invitations = @all_invitations.select { |i| i.response.nil? }
  end
end

app/helpers/event_helper.rb
module EventHelper
  def google_calendar_url(event)
    URI::HTTPS.build(
      host: 'www.google.com',
      path: '/calendar/b/0/render',
      query: ({
        action: 'TEMPLATE',
        text: event.title,
        dates: "#{event.start_time.strftime('%Y%m%dT%H%M00')}/#{(event.start_time + 60.minutes)
                .strftime('%Y%m%dT%H%M00')}",
        details: '',
        location: "#{event.location.address}, #{event.location.city} #{event.location.state}",
        trp: 'false',
        description: event.description,
        pli: '1',
        sf: 'true',
        output: 'xml'
      }).to_query
    ).to_s
  end

  def static_map_url(location, map_size = '300x300', zoom = 13)
    url = "http://maps.googleapis.com/maps/api/staticmap?sensor=true&markers=color:blue|#{location.to_s}"
    url << "&size=#{map_size}&zoom=#{zoom}"
  end
end

app/views/events/_buttons.html.haml
.actions_grouping
  / planner only options
  - if can? 'edit', @event
    = icon_button_link_to "Edit invitation", edit_event_path(@event), 'edit'

    = icon_button_link_to "Plan next week's game", duplicate_for_next_week_event_path(@event), 'copy'

    = icon_button_link_to "Resend invitations", resend_invitations_event_path(@event), 'bullhorn'

  / all invited users options
  = icon_button_link_to "Invite your subs", show_subs_event_path(@event), 'exchange'

  = icon_button_link_to "Find subs", show_same_day_subs_event_path(@event), 'search'

  = icon_button_link_to "Send Email", new_email_event_path(@event), 'envelope'
  = icon_button_link_to "Add to Google Calendar", google_calendar_url(@event), 'calendar'


  / / amazon ad
  / .amazon_ad
  /   If you're going to purchase anything from Amazon, click through the link below and help support Teamsubs
  /   <iframe src="http://rcm-na.amazon-adsystem.com/e/cm?t=nohandles-20&o=1&p=21&l=ur1&category=sss&banner=0FWR859ZNRNZ4QXGWDG2&f=ifr" width="125" height="125" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>

app/views/events/_event.html.haml
.event_listing.row
  .col-md-6= link_to event.title,  event_path(event)
  .col-md-3= l event.start_time, :format => :us
  .col-md-3= event.location.name

app/views/events/_fields.html.haml
.row
  .col-md-6
    = f.input :title, :required => false
    = f.input :description, :input_html => {:class => 'span4'}
    = f.input :start_time, :as => :ui_date_time_picker

    - sport_id = @event.location ? @event.sport_id : Sport.first.id
    = select_tag "sport", options_from_collection_for_select(Sport.all, "id", "name", selected: sport_id), :onchange => "getLocations(this);", :class => 'form-control'

    = f.input :schedule_link, :label => 'Link to schedule'

    - if @event.location.nil?
      = f.association :location, :collection => Sport.first.locations
    - else
      = f.association :location
    = button_link_to "Location not found??", new_location_path

.row
  .col-md-12
    %h3 Invite Players
    %h4 Primary Rosters are invited immediately.  Others are subs you can invite later.
    = f.simple_fields_for :rosters do |r|
      .col-md-12
        .primary.col-md-12= render 'roster_fields', :f => r


.clearfix
.row
  .col-md-12
    %p= f.link_to_add "Add another roster", :rosters, :primary => true

app/views/events/_responses.html.haml
.labels.col-md-12.col-xs.12.row.response_counts
  .bg-green.count-box.col-md-3.col-xs-12
    Yes
    .count
      = @event.yes_invitations.count
  .bg-orange.count-box.col-md-3.col-xs-12
    Maybe
    .count
      = @event.maybe_invitations.count
  .bg-red.count-box.col-md-3.col-xs-12
    No
    .count
      = @event.no_invitations.count
  .bg-gray.count-box.col-md-3.col-xs-12
    Not Yet Replied
    .count
      = @event.not_yet_replied_invitations.count

.response_list.col-md-12
  - @event.yes_invitations.each do |invitation|
    = render invitation

  - @event.maybe_invitations.each do |invitation|
    = render invitation

  - @event.no_invitations.each do |invitation|
    = render invitation

  - @event.not_yet_replied_invitations.each do |invitation|
    = render invitation

app/views/events/_roster_fields.html.haml
= f.input :primary, value: f.object.primary, label: 'Primary'
= f.input :comma_separated_emails, :as => :text

app/views/events/_weather.haml
.weather
  .temperature
    = "#{weather.currently.temperature.round}&deg;".html_safe
  .summary
    = weather.currently.summary

  .weather_disclaimer
    = link_to "Powered by Forecast", "http://www.forecast.io", target: '_blank'

app/views/events/deliver_thank_yous.html.haml
%p Thank you sent for
- @events.each do |event|
  %br= event.title

app/views/events/index.html.haml
= render @events
= paginate @events

app/views/events/new_email.html.haml
= simple_form_for @event, :url => deliver_email_event_path(@event), :method => :put do |f|
  = f.input :email_body, :as => :text, :input_html => {:class => 'span10'}
  = f.association :users, :as => :check_boxes, :collection => @event.users, :label_method => :display_name

  = f.button :submit, 'Send email', :class => 'btn-primary'

app/views/events/show.html.haml
#event_details.box.col-md-3.col-xs-12
  #time
    .time= @event.start_time.strftime('%I:%M%P')
  .full
    = @event.planner_user.name
    %br
    = l @event.start_time, :format => :us

#event_location.box.col-md-3.col-xs-12{:style => "background-image:url('#{static_map_url(@event.location)}');"}
  #location
    = render 'locations/multiline', :location => @event.location

#event_weather.box.col-md-3.col-xs-12
  #weather_container
    - weather = @event.weather
    = render 'events/weather', :weather => weather if weather

#response_input.box.col-md-3.col-xs-12{style: 'z-index:10;'}
  #selection
    - if @current_user_invitation
      = form_for @current_user_invitation, :method => 'put', :remote => true, :html => {:class => 'reload'} do |f|
        .col-md-12.btn-group.response_radios{data:{toggle: 'buttons'}}
          %label
            Can you play?
          .clearfix
          %label.btn.btn-primary
            Yes
            = f.radio_button('response', Invitation.yes)
          %label.btn.btn-primary
            No
            = f.radio_button('response', Invitation.no)
          %label.btn.btn-primary
            Maybe
            = f.radio_button('response', Invitation.maybe)
        .clearfix
        = f.text_field :comment,:label => false
      :javascript
        $('input[name="invitation[response]"]').change( function() {
          $(this.form).trigger('submit.rails');
        });


#event_description_and_buttons.box2.col-md-4.col-xs-12
  #title
    = @event.title
  #event_description
    = @event.description
    - if @event.schedule_link
      %p
        %a{:href => @event.schedule_link.to_s, :target => "_blank"} Link to schedule
  #actions
    = render 'buttons'

#event_responses.box2.col-md-8.col-xs-12
  = render "responses"

%p{:style => "clear:both;"}
:javascript
  jQuery("a").attr('data-ajax', 'false');

app/views/events/show_same_day_subs.html.haml
- if @users.empty?
  %h2 Sorry, no other players are available near the time of your game.

.subs_list
  - @users.each do |user|
    = render 'users/sub', :user => user

app/views/events/show_subs.html.haml
- if @users.empty?
  %h2 Sorry, you have no subs that aren't already invited

.subs_list
  - @users.each do |user|
    = render 'users/sub', :user => user