config/routes.rb
Teamsubs::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  devise_for :users
  match '/auth/facebook/' => 'authentications#facebook', :as => 'facebook_connect', via: [:get, :post]

  resources :users, only: [:show, :index]

  resources :events do
    member do
      get :duplicate_for_next_week
      get :resend_invitations
      get :new_email
      put :deliver_email
      get :show_subs
      get :show_same_day_subs
    end
    collection do
      get :deliver_thank_yous
    end
    resources :invitations, only: [:create]
  end

  resources :sports, only: [] do
    member do
      get :locations
    end
  end

  resources :locations, only: [:new, :create, :show]
  resources :invitations, only: [:show, :edit, :update] do
    member do
      get :open_tracker
    end
  end

  match 'invite/:id/:token(/:response)' => 'invitations#respond_from_email', :as => 'invite_with_token', via: [:get, :post]
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]
  post 'sendgrid/events_callback' => 'sendgrid#events_callback'

  # LEGACY STUFF
  match 'invitation/:invite_hash' => 'invitations#legacy_respond_from_email', via: [:get, :post]
  match 'respondfromemail/:invite_hash' => 'invitations#legacy_respond_from_email', via: [:get, :post]
  match 'copy/:invite_hash' => 'events#legacy_duplicate', via: [:get, :post]

  # render nothing routes for devices that just won't quit requesting garbage routes
  [ 'wp-trackback.php',
    'apple-touch-icon-precomposed.png',
    'customer/account/forgotpassword',
    'forum'
  ].each do |garbage_path|
    match garbage_path => 'home#not_found', via: [:post, :get]
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Teamsubs", root_path, :class => 'navbar-brand'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li
            = link_to 'Schedule game', new_event_path
          %li
            = link_to 'Logout', destroy_user_session_path, :method=>'delete'
          %li
            = link_to 'Edit account', edit_user_registration_path
          - if current_user.admin?
            %li
              = link_to 'Admin', users_path
          - if current_user.connected_to_facebook?
            %li
              .avatar
                %img{:src => (current_user.avatar_url)}
          - else
            %li
              = link_to 'Connect with Facebook', facebook_connect_path

        - else
          %li
            = link_to 'Login', new_user_session_path
          %li
            = link_to 'Sign up', new_user_registration_path
      %ul.nav.navbar-nav.pull-right
        %li
          = link_to 'Contact us', 'mailto:support@teamsubs.com'

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Teamsubs"
    %meta{:content => "Teamsubs", :property => "og:title"}
    %meta{:content => "website", :property => "og:type"}/
    %meta{:content => "http://www.teamsubs.com", :property => "og:url"}/
    %meta{:content => "http://www.teamsubs.com/assets/teamsubs.png", :property => "og:image"}/
    %meta{:content => "Teamsubs", :property => "og:site_name"}/
    %meta{:content => "Scheduling recreational sports sucks less at Teamsubs", :property => "og:description"}/
    %meta{:property => "fb:app_id", :content => "#{ENV['FACEBOOK_APP_ID']}"}
    %meta{:name => "msapplication-config", :content => "none"}
    %link{rel: "apple-touch-icon", href: asset_path('teamsubs.png') }
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/themes/smoothness/jquery-ui.css"
    = csrf_meta_tags
    %link{:href => 'http://fonts.googleapis.com/css?family=Metrophobic', :rel => 'stylesheet', :type => 'text/css'}

    = yield(:head)
  %body{:class => [controller.controller_name, controller.action_name]}
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-6624201-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    = render 'common/fb_js'

    = render 'layouts/navigation'

    #main{:role => "main"}
      .container
        .content
          = render 'layouts/messages'
          = yield
        %footer
          %iframe{:border => "0", :frameborder => "0", :height => "90", :marginwidth => "0", :scrolling => "no", :src => "http://rcm-na.amazon-adsystem.com/e/cm?t=teamsubs0a-20&o=1&p=48&l=ur1&category=sports&banner=1X1KH7BDVA8RZBJQEN82&f=ifr&linkID=CTIGVN67QPLDCJP7", :style => "border:none;", :width => "728"}